# Generated by Django 3.1.8 on 2022-07-18 19:56

from django.db import migrations, models
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0002_auto_20220718_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Nome da Disciplina'),
        ),
        migrations.CreateModel(
            name='PreRequirements',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disciplines', models.ManyToManyField(blank=True, to='Disciplines.Discipline', verbose_name='pre-requesitos')),
            ],
            options={
                'verbose_name': 'Pre-requisitos',
                'verbose_name_plural': 'Pre-requisitos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CoRequirements',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disciplines', models.ManyToManyField(blank=True, to='Disciplines.Discipline', verbose_name='co-requesitos')),
            ],
            options={
                'verbose_name': 'Co-requisitos',
                'verbose_name_plural': 'Co-requisitos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
