# Generated by Django 3.1.8 on 2022-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0003_auto_20220718_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='compoent_type',
            field=models.SmallIntegerField(choices=[('0', 'DISCIPLINAS'), ('1', 'MODULOS'), ('2', 'BLOCOS'), ('3', 'ATIVIDADE ACADEMICA')], default=0, verbose_name='Tipo do Componente Curricular'),
        ),
    ]
