# Generated by Django 3.1.8 on 2022-07-18 20:08

from django.db import migrations, models
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0006_discipline_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalences',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disciplines', models.ManyToManyField(blank=True, to='Disciplines.Discipline', verbose_name='equivalencias')),
            ],
            options={
                'verbose_name': 'Equivalencias',
                'verbose_name_plural': 'Equivalencias',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
