# Generated by Django 3.1.8 on 2022-07-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0007_equivalences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='exams',
            new_name='total_exams',
        ),
        migrations.AddField(
            model_name='discipline',
            name='code',
            field=models.CharField(max_length=48, null=True, verbose_name='Código da Disciplina'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Descrição da Ementa'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='flexible_program',
            field=models.BooleanField(default=True, verbose_name='Hoário Flexivel ?'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='long_description',
            field=models.FileField(blank=True, null=True, upload_to='disciplines/description/', verbose_name='Descrição da Ementa'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='online_registry',
            field=models.BooleanField(default=True, verbose_name='Matricula Online ?'),
        ),
    ]
