# Generated by Django 3.1.8 on 2022-07-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0008_auto_20220719_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='compoent_type',
            new_name='component_type',
        ),
    ]
