# Generated by Django 3.1.8 on 2022-07-19 06:03

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('Disciplines', '0009_auto_20220719_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceReview',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=255, null=True, verbose_name='Avaliação do Estudante')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Nota da avaliação')),
                ('disciplines', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Disciplines.discipline', verbose_name='Disciplina')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.student', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação da disciplina',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
