# Generated by Django 3.1.8 on 2022-07-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('Disciplines', '0010_customerservicereview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerServiceReview',
            new_name='DisciplinesReviews',
        ),
    ]
