# Generated by Django 3.1.8 on 2022-07-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('Disciplines', '0011_auto_20220719_0606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisciplinesReviews',
            new_name='DisciplineReviews',
        ),
    ]
