# Generated by Django 3.1.8 on 2022-07-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0015_auto_20220719_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalences',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='equivalences', to='Disciplines.Discipline', verbose_name='equivalencias'),
        ),
    ]
